using System.Diagnostics;

namespace CertStudy.Forms;

/// <summary>
/// Disclaimer dialog shown on first launch.
/// </summary>
class DisclaimerForm : Form
{
    private readonly CheckBox _dontShowCheckBox;
    private readonly Button _acceptButton;

    public bool DontShowAgain => _dontShowCheckBox.Checked;

    public DisclaimerForm()
    {
        Text = "IMPORTANT - Please Read";
        BackColor = SynthwaveColors.DarkPanel;
        ForeColor = SynthwaveColors.TextPrimary;
        Font = new Font("Consolas", 10f);
        StartPosition = FormStartPosition.CenterScreen;
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        ClientSize = new Size(560, 420);
        DoubleBuffered = true;

        // Title
        var titleLabel = new Label
        {
            Text = "⚠️  IMPORTANT - PLEASE READ",
            Dock = DockStyle.Top,
            Height = 50,
            Font = new Font("Consolas", 14f, FontStyle.Bold),
            ForeColor = SynthwaveColors.StatusAmber,
            TextAlign = ContentAlignment.MiddleCenter,
            Padding = new Padding(0, 12, 0, 0),
        };

        // Content
        var contentPanel = new Panel
        {
            Dock = DockStyle.Fill,
            BackColor = Color.Transparent,
            Padding = new Padding(20, 10, 20, 10),
        };

        var content = new RichTextBox
        {
            Dock = DockStyle.Fill,
            BackColor = SynthwaveColors.DarkPanel,
            ForeColor = SynthwaveColors.TextPrimary,
            BorderStyle = BorderStyle.None,
            ReadOnly = true,
            Font = new Font("Consolas", 10f),
            DetectUrls = true,
        };

        content.Text = @"
These practice questions were generated by AI (GitHub Copilot) based on publicly available Nutanix exam blueprints and documentation.

They have been through multiple validation passes but have NOT been reviewed or endorsed by Nutanix, Inc.

Actual certification exam questions will differ. Use this material as one study resource among several — do not rely on it exclusively.

Verify critical technical details (version numbers, feature names, UI specifics, exact syntax) against official Nutanix documentation at portal.nutanix.com before your exam.

Nutanix is a registered trademark of Nutanix, Inc. This material is not affiliated with or endorsed by Nutanix.
";

        content.SelectionStart = 0;
        content.Select(0, content.Text.Length);
        content.SelectionColor = SynthwaveColors.TextPrimary;

        // Highlight specific parts
        HighlightText(content, "NOT been reviewed or endorsed by Nutanix, Inc.", SynthwaveColors.StatusAmber);
        HighlightText(content, "do not rely on it exclusively", SynthwaveColors.StatusAmber);
        HighlightText(content, "portal.nutanix.com", SynthwaveColors.NeonCyan);

        content.LinkClicked += (s, e) =>
        {
            try
            {
                Process.Start(new ProcessStartInfo(e.LinkText!) { UseShellExecute = true });
            }
            catch { }
        };

        contentPanel.Controls.Add(content);

        // Checkbox panel
        var checkboxPanel = new Panel
        {
            Dock = DockStyle.Bottom,
            Height = 40,
            BackColor = Color.Transparent,
            Padding = new Padding(20, 0, 20, 0),
        };

        _dontShowCheckBox = new CheckBox
        {
            Text = "Don't show this message again",
            ForeColor = SynthwaveColors.TextDim,
            BackColor = Color.Transparent,
            Font = new Font("Consolas", 9f),
            CheckAlign = ContentAlignment.MiddleLeft,
            AutoSize = true,
        };

        checkboxPanel.Controls.Add(_dontShowCheckBox);

        // Button panel
        var buttonPanel = new Panel
        {
            Dock = DockStyle.Bottom,
            Height = 60,
            BackColor = Color.Transparent,
            Padding = new Padding(0, 10, 0, 10),
        };

        _acceptButton = new Button
        {
            Text = "I Understand, Continue",
            Size = new Size(200, 36),
            Enabled = false,
            BackColor = SynthwaveColors.NeonPurple,
            ForeColor = Color.White,
            FlatStyle = FlatStyle.Flat,
            Font = new Font("Consolas", 10f, FontStyle.Bold),
            Cursor = Cursors.Hand,
        };
        _acceptButton.FlatAppearance.BorderSize = 0;

        // Center the button
        _acceptButton.Location = new Point((buttonPanel.Width - _acceptButton.Width) / 2, 12);
        buttonPanel.Resize += (s, e) =>
        {
            _acceptButton.Location = new Point((buttonPanel.Width - _acceptButton.Width) / 2, 12);
        };

        buttonPanel.Controls.Add(_acceptButton);

        // Checkbox enables button
        _dontShowCheckBox.CheckedChanged += (s, e) =>
        {
            _acceptButton.Enabled = _dontShowCheckBox.Checked;
        };

        _acceptButton.Click += (s, e) =>
        {
            DialogResult = DialogResult.OK;
            Close();
        };

        Controls.Add(contentPanel);
        Controls.Add(checkboxPanel);
        Controls.Add(buttonPanel);
        Controls.Add(titleLabel);
    }

    private static void HighlightText(RichTextBox rtb, string text, Color color)
    {
        int index = rtb.Text.IndexOf(text);
        if (index >= 0)
        {
            rtb.Select(index, text.Length);
            rtb.SelectionColor = color;
        }
    }

    protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
    {
        if (keyData == Keys.Escape)
        {
            DialogResult = DialogResult.Cancel;
            Close();
            return true;
        }
        return base.ProcessCmdKey(ref msg, keyData);
    }
}
