// pdfExportService.js — PDF export using pdfkit (port of C# ExportService.cs)
// Generates professionally formatted exam PDFs with title pages, numbered
// questions, optional answer keys, and page headers/footers.

'use strict';

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// ─── Colours (synthwave-inspired, print-friendly) ───────────────────────────

const ACCENT_CYAN    = '#00C8FF';
const ACCENT_MAGENTA = '#FF2D95';
const CORRECT_GREEN  = '#00B450';
const TEXT_COLOR     = '#1E1E1E';
const DIM_GRAY       = '#646464';
const HEADER_BG      = '#0B0B1A';
const LIGHT_BG       = '#F5F5FA';

// ─── Layout constants (Letter: 612 × 792 pt) ───────────────────────────────

const PAGE_WIDTH     = 612;
const PAGE_HEIGHT    = 792;
const MARGIN_LEFT    = 50;
const MARGIN_RIGHT   = 50;
const MARGIN_TOP     = 60;
const FOOTER_Y       = 750;
const CONTENT_WIDTH  = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Returns a short description string for the exam.
 * @param {string} examName
 * @returns {string}
 */
function getExamInfo(examName) {
  if (examName.includes('NCP-AI'))  return '75 MCQ | 120 minutes | AI Infrastructure';
  if (examName.includes('NCP-US')) return '75 MCQ | 120 minutes | Unified Storage';
  if (examName.includes('NCP-CI')) return '75 MCQ | 120 minutes | Cloud Integration';
  if (examName.includes('NCM-MCI')) return '16–20 Live Lab | 180 minutes | Multicloud Infrastructure (Master)';
  return '';
}

/**
 * Returns "Select N" instruction text for multi-select questions.
 * @param {number} count
 * @returns {string}
 */
function selectLabel(count) {
  const words = ['', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE'];
  return count > 1 ? ` (Select ${words[count] || count})` : '';
}

/**
 * Estimates vertical space (pt) a question will consume.
 * Used to decide whether to insert a page break.
 * @param {object} q
 * @param {boolean} includeAnswers
 * @returns {number}
 */
function estimateHeight(q, includeAnswers) {
  const stemLines = Math.ceil((q.questionText || '').length / 85);
  let h = 24 + Math.max(stemLines, 1) * 14;
  h += (q.options ? q.options.length : 0) * 15;
  if (includeAnswers) {
    h += 18;
    if (q.explanation) {
      h += 14 + Math.ceil(q.explanation.length / 90) * 12;
    }
  }
  return Math.max(h, 60);
}

// ─── Page-level drawing helpers ─────────────────────────────────────────────

/**
 * Draws the dark header bar at the top of a content page.
 * @param {PDFDocument} doc
 * @param {string} examName
 */
function drawHeader(doc, examName) {
  doc.save();
  doc.rect(0, 0, PAGE_WIDTH, 28).fill(HEADER_BG);
  doc.fontSize(8).font('Helvetica-Bold').fillColor(ACCENT_CYAN)
    .text(examName, 14, 8, { width: 300 });
  doc.rect(0, 28, PAGE_WIDTH, 1.5).fill(ACCENT_MAGENTA);
  doc.restore();
}

/**
 * Draws the page footer with page number.
 * @param {PDFDocument} doc
 * @param {number} pageNum
 */
function drawFooter(doc, pageNum) {
  doc.save();
  doc.fontSize(7.5).font('Helvetica').fillColor(DIM_GRAY);
  doc.text('Nutanix Certification Study Tool', MARGIN_LEFT, FOOTER_Y, { width: 300 });
  doc.text(`Page ${pageNum}`, 0, FOOTER_Y, { width: PAGE_WIDTH, align: 'center' });
  doc.restore();
}

// ─── Title page ─────────────────────────────────────────────────────────────

/**
 * Adds an exam title page to the document.
 * @param {PDFDocument} doc
 * @param {string} examName
 * @param {number} questionCount
 */
function addTitlePage(doc, examName, questionCount) {
  // Dark header band
  doc.rect(0, 0, PAGE_WIDTH, 120).fill(HEADER_BG);
  doc.fontSize(20).font('Helvetica-Bold').fillColor(ACCENT_CYAN)
    .text('NUTANIX EXAM PREP', 0, 35, { width: PAGE_WIDTH, align: 'center' });
  doc.fontSize(14).font('Helvetica').fillColor('#FFFFFF')
    .text(examName, 0, 72, { width: PAGE_WIDTH, align: 'center' });

  // Accent stripe
  doc.rect(0, 120, PAGE_WIDTH, 3).fill(ACCENT_MAGENTA);

  // Question count
  doc.fontSize(18).font('Helvetica-Bold').fillColor(TEXT_COLOR)
    .text(`${questionCount} Practice Questions`, 0, 200, { width: PAGE_WIDTH, align: 'center' });

  // Exam info
  const info = getExamInfo(examName);
  if (info) {
    doc.fontSize(14).font('Helvetica').fillColor(DIM_GRAY)
      .text(info, 0, 240, { width: PAGE_WIDTH, align: 'center' });
  }

  // Bottom attribution
  doc.fontSize(7.5).font('Helvetica').fillColor(DIM_GRAY)
    .text('Generated by Nutanix Certification Study Tool', 0, PAGE_HEIGHT - 40, {
      width: PAGE_WIDTH,
      align: 'center',
    });
}

// ─── Grand title page (for combined export) ─────────────────────────────────

/**
 * Adds a grand title page listing all exams.
 * @param {PDFDocument} doc
 * @param {number} totalQuestions
 */
function addGrandTitlePage(doc, totalQuestions) {
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT).fill(HEADER_BG);

  doc.fontSize(32).font('Helvetica-Bold').fillColor(ACCENT_CYAN)
    .text('NUTANIX', 0, 200, { width: PAGE_WIDTH, align: 'center' });
  doc.fontSize(20).font('Helvetica').fillColor('#FFFFFF')
    .text('Certification Study Guide', 0, 250, { width: PAGE_WIDTH, align: 'center' });

  const examNames = [
    'NCP-AI 6.10 — AI Infrastructure',
    'NCP-US 6.10 — Unified Storage',
    'NCP-CI 6.10 — Cloud Integration',
    'NCM-MCI 6.10 — Multicloud Infrastructure (Master)',
  ];

  doc.fontSize(12).font('Helvetica').fillColor(ACCENT_MAGENTA);
  let ey = 340;
  for (const name of examNames) {
    doc.text(`•  ${name}`, PAGE_WIDTH / 2 - 200, ey, { width: 400 });
    ey += 28;
  }

  doc.fontSize(14).font('Helvetica-Bold').fillColor(ACCENT_CYAN)
    .text(`${totalQuestions} Practice Questions — Fully Validated`, 0, ey + 30, {
      width: PAGE_WIDTH,
      align: 'center',
    });
}

// ─── Question rendering ─────────────────────────────────────────────────────

/**
 * Draws a single question and returns the new Y cursor position.
 * @param {PDFDocument} doc
 * @param {object} q — Question object
 * @param {number} num — 1-based question number
 * @param {number} y — current Y position
 * @param {boolean} includeAnswers
 * @returns {number} updated Y position
 */
function drawQuestion(doc, q, num, y, includeAnswers) {
  // Light background card
  const cardHeight = estimateHeight(q, includeAnswers);
  doc.save();
  doc.rect(MARGIN_LEFT - 8, y - 4, CONTENT_WIDTH + 16, cardHeight).fill(LIGHT_BG);
  doc.restore();

  // Multi-select label
  const multiHint = q.correctAnswers && q.correctAnswers.length > 1
    ? selectLabel(q.correctAnswers.length)
    : '';

  // Question number + stem
  doc.fontSize(10).font('Helvetica-Bold').fillColor(ACCENT_MAGENTA)
    .text(`Q${num}.${multiHint}`, MARGIN_LEFT, y, { continued: false });
  y += 15;

  doc.fontSize(9.5).font('Helvetica').fillColor(TEXT_COLOR);
  doc.text(q.questionText || '', MARGIN_LEFT + 20, y, { width: CONTENT_WIDTH - 30 });
  y = doc.y + 6;

  // Options
  const options = q.options || [];
  for (const opt of options) {
    const letter = (opt.letter || '').toUpperCase();
    const isCorrect = includeAnswers && q.correctAnswers &&
      q.correctAnswers.map(a => a.toUpperCase()).includes(letter);

    if (isCorrect) {
      doc.font('Helvetica-Bold').fillColor(CORRECT_GREEN);
      doc.text(`  ✓ ${letter}) ${opt.text || ''}`, MARGIN_LEFT + 16, y, { width: CONTENT_WIDTH - 40 });
    } else {
      doc.font('Helvetica').fillColor(TEXT_COLOR);
      doc.text(`     ${letter}) ${opt.text || ''}`, MARGIN_LEFT + 16, y, { width: CONTENT_WIDTH - 40 });
    }
    y = doc.y + 2;
  }

  // Answer line
  if (includeAnswers && q.correctAnswers && q.correctAnswers.length > 0) {
    y += 2;
    const answers = q.correctAnswers.map(a => a.toUpperCase()).join(', ');
    doc.fontSize(9).font('Helvetica-Bold').fillColor(CORRECT_GREEN)
      .text(`Answer: ${answers}`, MARGIN_LEFT + 16, y);
    y = doc.y + 2;

    // Explanation
    if (q.explanation) {
      doc.fontSize(8.5).font('Helvetica-Oblique').fillColor(DIM_GRAY)
        .text(q.explanation, MARGIN_LEFT + 16, y, { width: CONTENT_WIDTH - 40 });
      y = doc.y + 2;
    }
  }

  return y;
}

// ─── Answer key page ────────────────────────────────────────────────────────

/**
 * Adds a compact answer-key page at the end of an exam section.
 * @param {PDFDocument} doc
 * @param {string} examName
 * @param {Array} questions
 */
function addAnswerKeyPage(doc, examName, questions) {
  doc.addPage({ size: 'Letter' });

  doc.fontSize(16).font('Helvetica-Bold').fillColor(TEXT_COLOR)
    .text(`${examName} — Answer Key`, MARGIN_LEFT, 40, { width: CONTENT_WIDTH });
  doc.rect(MARGIN_LEFT, 68, CONTENT_WIDTH, 1.5).fill(ACCENT_MAGENTA);

  doc.fontSize(9).font('Courier').fillColor(TEXT_COLOR);

  const COL_COUNT = 4;
  const colWidth = CONTENT_WIDTH / COL_COUNT;
  let y = 85;
  let col = 0;

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const answers = (q.correctAnswers || []).map(a => a.toUpperCase()).join(',');
    const numStr = String(i + 1).padStart(3, ' ');
    const line = `Q${numStr}: ${answers}`;
    const x = MARGIN_LEFT + col * colWidth;
    doc.text(line, x, y, { width: colWidth, lineBreak: false });
    y += 13;

    if (y > FOOTER_Y - 30) {
      y = 85;
      col++;
      if (col >= COL_COUNT) {
        col = 0;
        doc.addPage({ size: 'Letter' });
        doc.fontSize(16).font('Helvetica-Bold').fillColor(TEXT_COLOR)
          .text(`${examName} — Answer Key (cont.)`, MARGIN_LEFT, 40, { width: CONTENT_WIDTH });
        doc.rect(MARGIN_LEFT, 68, CONTENT_WIDTH, 1.5).fill(ACCENT_MAGENTA);
        doc.fontSize(9).font('Courier').fillColor(TEXT_COLOR);
      }
    }
  }
}

// ─── Public API ─────────────────────────────────────────────────────────────

/**
 * Exports a single exam to a PDF file (or Buffer).
 *
 * @param {string}  examName       — Display name for the exam (e.g. "NCP-AI 6.10")
 * @param {Array}   questions      — Array of Question-shaped objects
 * @param {boolean} includeAnswers — Whether to highlight correct answers and show explanations
 * @param {string}  [outputPath]   — File path to write. If omitted, returns a Buffer.
 * @param {object}  [pdfOptions]   — Extra options forwarded to PDFDocument (e.g. { compress: false })
 * @returns {Promise<Buffer>} Resolves with the PDF content as a Buffer.
 */
function exportExam(examName, questions, includeAnswers, outputPath, pdfOptions) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'Letter',
      margins: { top: MARGIN_TOP, bottom: 50, left: MARGIN_LEFT, right: MARGIN_RIGHT },
      info: {
        Title: `Nutanix ${examName} Practice Questions`,
        Author: 'Nutanix Certification Study Tool',
      },
      autoFirstPage: true,
      ...pdfOptions,
    });

    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks);
      if (outputPath) {
        try {
          fs.mkdirSync(path.dirname(outputPath), { recursive: true });
          fs.writeFileSync(outputPath, buffer);
        } catch (err) {
          return reject(err);
        }
      }
      resolve(buffer);
    });

    // --- Title page ---
    addTitlePage(doc, examName, questions.length);

    // --- Content pages ---
    let pageNum = 2;
    doc.addPage({ size: 'Letter' });
    drawHeader(doc, examName);
    let y = MARGIN_TOP;

    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      const needed = estimateHeight(q, includeAnswers);

      if (y + needed > FOOTER_Y - 20) {
        drawFooter(doc, pageNum);
        doc.addPage({ size: 'Letter' });
        pageNum++;
        drawHeader(doc, examName);
        y = MARGIN_TOP;
      }

      y = drawQuestion(doc, q, i + 1, y, includeAnswers);
      y += 12;
    }

    drawFooter(doc, pageNum);

    // --- Answer key ---
    if (includeAnswers) {
      addAnswerKeyPage(doc, examName, questions);
    }

    doc.end();
  });
}

/**
 * Exports multiple exams into a single combined PDF.
 *
 * @param {Object<string, Array>} exams — Map of examName → question arrays
 * @param {boolean} includeAnswers
 * @param {string}  [outputPath]
 * @param {object}  [pdfOptions]   — Extra options forwarded to PDFDocument
 * @returns {Promise<Buffer>}
 */
function exportAll(exams, includeAnswers, outputPath, pdfOptions) {
  return new Promise((resolve, reject) => {
    const entries = Object.entries(exams);
    let totalQ = 0;
    for (const [, qs] of entries) totalQ += qs.length;

    const doc = new PDFDocument({
      size: 'Letter',
      margins: { top: MARGIN_TOP, bottom: 50, left: MARGIN_LEFT, right: MARGIN_RIGHT },
      info: {
        Title: 'Nutanix Certification Study Guide — Complete',
        Author: 'Nutanix Certification Study Tool',
      },
      autoFirstPage: true,
      ...pdfOptions,
    });

    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('error', reject);
    doc.on('end', () => {
      const buffer = Buffer.concat(chunks);
      if (outputPath) {
        try {
          fs.mkdirSync(path.dirname(outputPath), { recursive: true });
          fs.writeFileSync(outputPath, buffer);
        } catch (err) {
          return reject(err);
        }
      }
      resolve(buffer);
    });

    // Grand title page
    addGrandTitlePage(doc, totalQ);

    // Each exam
    for (const [examName, questions] of entries) {
      doc.addPage({ size: 'Letter' });
      addTitlePage(doc, examName, questions.length);

      let pageNum = 1;
      doc.addPage({ size: 'Letter' });
      drawHeader(doc, examName);
      let y = MARGIN_TOP;

      for (let i = 0; i < questions.length; i++) {
        const q = questions[i];
        const needed = estimateHeight(q, includeAnswers);

        if (y + needed > FOOTER_Y - 20) {
          drawFooter(doc, pageNum);
          doc.addPage({ size: 'Letter' });
          pageNum++;
          drawHeader(doc, examName);
          y = MARGIN_TOP;
        }

        y = drawQuestion(doc, q, i + 1, y, includeAnswers);
        y += 12;
      }

      drawFooter(doc, pageNum);

      if (includeAnswers) {
        addAnswerKeyPage(doc, examName, questions);
      }
    }

    doc.end();
  });
}

module.exports = { exportExam, exportAll };
